from __future__ import unicode_literals

from ircproto.constants import *

reply_templates = {
    RPL_WELCOME: "Welcome to the Internet Relay Network {nickname}!{username}@{host}",
    RPL_YOURHOST: "Your host is {host}, running version {version}",
    RPL_CREATED: "This server was created {date}",
    RPL_MYINFO: "{servername} {version} {available_user_modes} {available_channel_modes}",
    RPL_BOUNCE: "Try server {server_name}, port {port_number}",
    RPL_USERHOST: None,
    RPL_ISON: None,
    RPL_AWAY: "{nick} :{away_message}",
    RPL_UNAWAY: ":You are no longer marked as being away",
    RPL_NOWAWAY: ":You have been marked as being away",
    RPL_WHOISUSER: "{nick} {user} {host} * :{real_name}",
    RPL_WHOISSERVER: "{nick} {server} :{server_info}",
    RPL_WHOISOPERATOR: "{nick} :is an IRC operator",
    RPL_WHOISSIDLE: "{nick} {integer} :seconds idle",
    RPL_ENDOFWHOIS: "{nick} :End of WHOIS list",
    RPL_WHOISCHANNELS: None,
    RPL_WHOWASUSER: "{nick} {user} {host} * :{real_name}",
    RPL_ENDOFWHOWAS: "{nick} :End of WHOWAS",
    RPL_LIST: "{channel} {visible} :{topic}",
    RPL_LISTEND: ":End of LIST",
    RPL_UNIQOPIS: "{channel} {nickname}",
    RPL_CHANNELMODEIS: "{channel} {mode} {mode_params}",
    RPL_NOTOPIC: "{channel} :No topic is set",
    RPL_TOPIC: "{channel} :{topic}",
    RPL_INVITING: "{channel} {nick}",
    RPL_SUMMONING: "{user} :Summoning user to IRC",
    RPL_INVITELIST: "{channel} {invitemask}",
    RPL_ENDOFINVITELIST: "{channel} :End of channel invite list",
    RPL_EXCEPTLIST: "{channel} {exceptionmask}",
    RPL_ENDOFEXCEPTLIST: "{channel} :End of channel exception list",
    RPL_VERSION: "{version}.{debuglevel} {server} :{comments}",
    RPL_WHOREPLY: "{channel} {user} {host} {server} {nick} {flags} :{hop_count} {real_name}",
    RPL_ENDOFWHO: "{name} :End of WHO list",
    RPL_NAMREPLY: None,
    RPL_ENDOFNAMES: "{channel} :End of NAMES list",
    RPL_LINKS: "{mask} {server} :{hopcount} {server_info}",
    RPL_ENDOFLINKS: "{mask} :End of LINKS list",
    RPL_BANLIST: "{channel} {banmask}",
    RPL_ENDOFBANLIST: "{channel} :End of channel ban list",
    RPL_INFO: ":{string}",
    RPL_ENDOFINFO: ":End of INFO list",
    RPL_MOTDSTART: ":- {server} Message of the day - ",
    RPL_MOTD: ":- {text}",
    RPL_ENDOFMOTD: ":End of MOTD command",
    RPL_YOUREOPER: ":You are now an IRC operator",
    RPL_REHASHING: "{config_file} :Rehashing",
    RPL_YOURESERVICE: "You are service {servicename}",
    RPL_TIME: "{server} :{string showing server's local time}",
    RPL_USERSSTART: ":UserID   Terminal  Host",
    RPL_USERS: ":{username} {ttyline} {hostname}",
    RPL_ENDOFUSERS: ":End of users",
    RPL_NOUSERS: ":Nobody logged in",
    RPL_TRACELINK: ("Link {version_debug_level} {destination} {next_server} V{protocol_version} "
                    "{link uptime in seconds} {backstream_sendq} {upstream_sendq}"),
    RPL_TRACECONNECTING: "Try. {class} {server}",
    RPL_TRACEHANDSHAKE: "H.S. {class} {server}",
    RPL_TRACEUNKNOWN: "???? {class} [{client IP address in dot form}]",
    RPL_TRACEOPERATOR: "Oper {class} {nick}",
    RPL_TRACEUSER: "User {class} {nick}",
    RPL_TRACESERVER: ("Serv {class} {int}S {int}C {server} {nick!user|*!*}@{host|server} "
                      "V{protocol_version}"),
    RPL_TRACESERVICE: "Service {class} {name} {type} {active_type}",
    RPL_TRACENEWTYPE: "{newtype} 0 {client_name}",
    RPL_TRACECLASS: "Class {class} {count}",
    RPL_TRACELOG: "File {logfile} {debug_level}",
    RPL_TRACEEND: "{server_name} {version & debug level} :End of TRACE",
    RPL_STATSLINKINFO: ("{linkname} {sendq} {sent_messages} {sent_kbytes} {received_messages} "
                        "{received_kbytes} {time_open}"),
    RPL_STATSCOMMANDS: "{command} {count} {byte_count} {remote_count}",
    RPL_ENDOFSTATS: "{stats_letter} :End of STATS report",
    RPL_STATSUPTIME: ":Server Up %d days %d:%02d:%02d",
    RPL_STATSOLINE: "O {hostmask} * {name}",
    RPL_UMODEIS: "{user_mode_string}",
    RPL_SERVLIST: "{name} {server} {mask} {type} {hopcount} {info}",
    RPL_SERVLISTEND: "{mask} {type} :End of service listing",
    RPL_LUSERCLIENT: ":There are {integer} users and {integer} services on {integer} servers",
    RPL_LUSEROP: "{integer} :operator(s) online",
    RPL_LUSERUNKNOWN: "{integer} :unknown connection(s)",
    RPL_LUSERCHANNELS: "{integer} :channels formed",
    RPL_LUSERME: ":I have {integer} clients and {integer} servers",
    RPL_ADMINME: "{server} :Administrative info",
    RPL_ADMINLOC1: ":{admin_info}",
    RPL_ADMINLOC2: ":{admin_info}",
    RPL_ADMINEMAIL: ":{admin_info}",
    RPL_TRYAGAIN: "{command} :Please wait a while and try again.",
    ERR_NOSUCHNICK: "{nickname} :No such nick/channel",
    ERR_NOSUCHSERVER: "{server_name} :No such server",
    ERR_NOSUCHCHANNEL: "{channel_name} :No such channel",
    ERR_CANNOTSENDTOCHAN: "{channel_name} :Cannot send to channel",
    ERR_TOOMANYCHANNELS: "{channel_name} :You have joined too many channels",
    ERR_WASNOSUCHNICK: "{nickname} :There was no such nickname",
    ERR_TOOMANYTARGETS: "{target} :{code} recipients. {message}",
    ERR_NOSUCHSERVICE: "{service_name} :No such service",
    ERR_NOORIGIN: ":No origin specified",
    ERR_NORECIPIENT: ":No recipient given ({command})",
    ERR_NOTEXTTOSEND: ":No text to send",
    ERR_NOTOPLEVEL: "{mask} :No toplevel domain specified",
    ERR_WILDTOPLEVEL: "{mask} :Wildcard in toplevel domain",
    ERR_BADMASK: "{mask} :Bad Server/host mask",
    ERR_UNKNOWNCOMMAND: "{command} :Unknown command",
    ERR_NOMOTD: ":MOTD File is missing",
    ERR_NOADMININFO: "{server} :No administrative info available",
    ERR_FILEERROR: ":File error doing {file_op} on {file}",
    ERR_NONICKNAMEGIVEN: ":No nickname given",
    ERR_ERRONEUSNICKNAME: "{nick} :Erroneous nickname",
    ERR_NICKNAMEINUSE: "{nick} :Nickname is already in use",
    ERR_NICKCOLLISION: "{nick} :Nickname collision KILL from {user@{host}",
    ERR_UNAVAILRESOURCE: "{nick/channel} :Nick/channel is temporarily unavailable",
    ERR_USERNOTINCHANNEL: "{nick} {channel} :They aren't on that channel",
    ERR_NOTONCHANNEL: "{channel} :You're not on that channel",
    ERR_USERONCHANNEL: "{user} {channel} :is already on channel",
    ERR_NOLOGIN: "{user} :User not logged in",
    ERR_SUMMONDISABLED: ":SUMMON has been disabled",
    ERR_USERSDISABLED: ":USERS has been disabled",
    ERR_NOTREGISTERED: ":You have not registered",
    ERR_NEEDMOREPARAMS: "{command} :Not enough parameters",
    ERR_ALREADYREGISTRED: ":Unauthorized command (already registered)",
    ERR_NOPERMFORHOST: ":Your host isn't among the privileged",
    ERR_PASSWDMISMATCH: ":Password incorrect",
    ERR_YOUREBANNEDCREEP: ":You are banned from this server",
    ERR_YOUWILLBEBANNED: "",
    ERR_KEYSET: "{channel} :Channel key already set",
    ERR_CHANNELISFULL: "{channel} :Cannot join channel (+l)",
    ERR_UNKNOWNMODE: "{char} :is unknown mode char to me for {channel}",
    ERR_INVITEONLYCHAN: "{channel} :Cannot join channel (+i)",
    ERR_BANNEDFROMCHAN: "{channel} :Cannot join channel (+b)",
    ERR_BADCHANNELKEY: "{channel} :Cannot join channel (+k)",
    ERR_BADCHANMASK: "{channel} :Bad Channel Mask",
    ERR_NOCHANMODES: "{channel} :Channel doesn't support modes",
    ERR_BANLISTFULL: "{channel} {char} :Channel list is full",
    ERR_NOPRIVILEGES: ":Permission Denied- You're not an IRC operator",
    ERR_CHANOPRIVSNEEDED: "{channel} :You're not channel operator",
    ERR_CANTKILLSERVER: ":You can't kill a server!",
    ERR_RESTRICTED: ":Your connection is restricted!",
    ERR_UNIQOPPRIVSNEEDED: ":You're not the original channel operator",
    ERR_NOOPERHOST: ":No O-lines for your host",
    ERR_UMODEUNKNOWNFLAG: ":Unknown MODE flag",
    ERR_USERSDONTMATCH: ":Cannot change mode for other users"
}
